name: Deploy Vue Site to GitHub Pages

on:
  push:
    branches:
      - main # or 'master', or any branch you want to trigger builds

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
